### ISSUE TITLE
在TINY*上复现结果过低

### ISSUE THREAD

**Issue by FryLcm** [TsingZ0/GPFL#6]
请问在TINY*上复现，除了学习率变为0.1以及使用resnet模型外，其他参数还需要调整吗？使用默认参数复现最好结果为0.39，达不到论文中的0.437.

**Comment by FryLcm** [comment]
-lam 0.01    -lamr 0.1

**Comment by TsingZ0** [comment]
对于resnet，我们采用`-lam 0.0001 -lamr 0.0`

![image](https://github.com/TsingZ0/GPFL/assets/24207672/aa8cc280-8ec7-4085-866e-21ccffea01d6)

**Comment by FryLcm** [comment]
> 对于resnet，我们采用`-lam 0.0001 -lamr 0.0`
> 
> ![image](https://private-user-images.githubusercontent.com/24207672/284568265-aa8cc280-8ec7-4085-866e-21ccffea01d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTc4NjAsIm5iZiI6MTcwMTIxNzU2MCwicGF0aCI6Ii8yNDIwNzY3Mi8yODQ1NjgyNjUtYWE4Y2MyODAtOGVjNy00MDg1LTg2NmUtMjFjY2ZmZWEwMWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAwMjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODk4MjJjMjE1MTk4MWY4ZjM5MTQyNTg3MTNlMDZkZmMyNTg2YjBmYjg0MGQ1ZjdlYTZmZDI2NzU5NDk3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_-8dkb2RQfiZYIHKik_MtVXTm9fx0Jm3kS9DHrwD8c)

我使用您的pfl框架中的gpfl算法，我在tiny数据集上使用resnet模型上复现结果为0.4559，但是使用cnn模型复现结果为0.4732。在resnet模型上的准确度小于cnn模型上，请问这样正常吗？

在您的论文中tiny复现结果为0.4337，tiny* 复现结果为0.4370。
我复现的 tiny 复现结果为0.4732，tiny*  上复现结果为0.4610。
请问这样的结果正常吗？tiny*复现结果要好于tiny。

**Comment by TsingZ0** [comment]
resnet模型上的准确度小于cnn模型这个现象是存在的，目前也有相关论文研究这一块，主要是batch normalization (BN)不适应FL中的non-iid问题造成的。比如：[Why Batch Normalization Damage Federated Learning on Non-IID Data?](https://arxiv.org/abs/2301.02982)。

我的pFL框架[PFLlib](https://github.com/TsingZ0/PFLlib)中的算法结果不一定能复现论文中的结果，因为随着PFLlib的发展，修改了底层代码，会出现不兼容的问题。建议使用本项目中的代码来复现结果。最新的PFLlib中Dataloader中shuffle=True，会影响BN中的统计过程，导致结果不一致。

**Comment by FryLcm** [comment]
> resnet模型上的准确度小于cnn模型这个现象是存在的，目前也有相关论文研究这一块，主要是batch normalization (BN)不适应FL中的non-iid问题造成的。比如：[Why Batch Normalization Damage Federated Learning on Non-IID Data?](https://arxiv.org/abs/2301.02982)。
> 
> 我的pFL框架[PFLlib](https://github.com/TsingZ0/PFLlib)中的算法结果不一定能复现论文中的结果，因为随着PFLlib的发展，修改了底层代码，会出现不兼容的问题。建议使用本项目中的代码来复现结果。最新的PFLlib中Dataloader中shuffle=True，会影响BN中的统计过程，导致结果不一致。

非常感谢您的回复
